# Generated by Django 5.1.3 on 2024-11-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipdriveDeals',
            fields=[
                ('deal_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('deal_name', models.CharField(max_length=255, unique=True)),
                ('deal_address', models.CharField(max_length=255, unique=True)),
                ('deal_zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('deal_phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('deal_email_address', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
